name: xpack-gcc

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build and Test HelloWorld...
      run: bazelisk test --config=xpack-gcc //HelloWorld:HelloWorld
      working-directory: Examples
